### ISSUE TITLE
Build for M5Stack Core2

### ISSUE THREAD

**Issue by cryptax** [armel/HAL9000#20]
Hello

I'm having troubles building the project for **M5 Core 2**. But I'm very possibly doing it wrong. Can you assist?

1. Shouldn't `platformio.ini` be modified to build on `m5stack-core2`, as such?

```
[env:core2]
 build_flags = ${env.build_flags} -DBOARD=2 -DBRIGHTNESS=32
 board_build.mcu = esp32
 board_build.flash_mode = qio
 board_build.f_cpu = 240000000L
 board_build.f_flash = 80000000L
-
-board = m5stack-fire
-
+board = m5stack-core2
```

2. When I do so (m5stack-core2), it does not compile:

```
 #include <HTTPClient.h>
          ^~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/core2/lib843/M5Core2/M5Display.cpp.o] Error 1
```

I haven't managed to find the correct _HTTPClient_ to include.
This is the **dependencies** I have so far:

```
[env:core2]
build_flags = ${env.build_flags} -DBOARD=2 -DBRIGHTNESS=32
board_build.mcu = esp32
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board = m5stack-core2
board_build.partitions = partitions.csv
lib_deps = 
	tobozo/ESP32-targz@^1.1.9
	fastled/FastLED@^3.6.0
	m5stack/M5Unified@^0.1.7
	bitbank2/JPEGDEC@^1.2.8
	m5stack/M5Core2@^0.1.5
```

I should include **M5Core2**, shouldn't I?
And then, there's an error with `HTTPClient.h` not found... 
I tried `amcewen/HttpClient@^2.2.0` and `mbed-kazushi2008/HTTPClient@0.0.0+sha.cf5d7427a9ec` but they did not solve the issue.
Thanks,

**Comment by armel** [comment]
Hello,

In platformio.ini, just change 

`default_envs = core 
`

by 

`default_envs = core2
`

This will modify the target build platform from Core to Core2.
That's all.

Last but not least, you need to flash the data folder content (with images, videos and wav) on the LittleFS Flash (Upload Filesystem Image)... 

Armel.

**Comment by armel** [comment]
By the way, if you don't know how to flash the data folder content (with images, videos and wav) on the LittleFS Flash, take a look at this [tutorial](https://www.donskytech.com/how-to-upload-filesystem-image-in-platformio-ide/).

Armel.

**Comment by cryptax** [comment]
> Hello,
> 
> In platformio.ini, just change
> 
> `default_envs = core `
> 
> by
> 
> `default_envs = core2 `

In the `env:core2` section of `platformio.ini`, currently there is `m5stack-fire` for the `board` setting. Is this *really* normal? I would expect it to be **m5stack-core2**. I thought it was a typo...

 ```
[env:core2]
build_flags = ${env.build_flags} -DBOARD=2 -DBRIGHTNESS=32

board_build.mcu = esp32
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

board = m5stack-fire
```

>By the way, if you don't know how to flash the data folder content (with images, videos and wav) on the LittleFS Flash, >take a look at this [tutorial](https://www.donskytech.com/how-to-upload-filesystem-image-in-platformio-ide/).

Thanks :) I'll look into it!

Axelle.

**Comment by armel** [comment]
Hi,

Board definition is not important here. This project uses M5Unified library 😌

So, replace `board = m5stack-fire` by `board = m5stack-core2` if you want. 
Result will be simply the same 🤗

I'm using `board = m5stack-fire` for Core (Basic, Grey, Fire, Metal, etc.) and Core2 (Core2, AWS, Tough, etc.) in my platformio.ini files since 2 years without any problem.

Armel.

**Comment by cryptax** [comment]
It's working :+1:  Thanks!
![halp9000](https://github.com/armel/HAL9000/assets/2493690/ab2fb837-16d0-41c3-9286-7b28acb70914)
